apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    labels:
        app: go-gtfs-import
    name: go-gtfs-import
    namespace: gtfs
spec:
    replicas: 1
    selector:
        matchLabels:
            app: go-gtfs-api
    strategy:
        rollingUpdate:
            maxSurge: 1
            maxUnavailable: 1
        type: RollingUpdate
    template:
        metadata:
            labels:
                app: go-gtfs-import
        spec:
            restartPolicy: Always
            containers:
              - image: eu.gcr.io/allbinary-204807/allbin/gtfs/go-gtfs-import:v0.1.1
                  name: go-gtfs-import
