name: Build and Deploy to GKE

on:
  push:
    branches:
    - master

env:
  GKE_PROJECT: ${{ secrets.GKE_PROJECT }}
  GKE_EMAIL: ${{ secrets.GKE_EMAIL }}
  GITHUB_SHA: ${{ github.sha }}
  GKE_ZONE: europe-west3-a
  GKE_CLUSTER: ab-cluster-1
  IMAGE_BASE: eu.gcr.io/${{ secrets.GKE_PROJECT }}/gtfs
  GO111MODULE: on
  CGO_ENABLED: 0

jobs:
  setup-build-publish-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - uses: actions/setup-go@v1
      with:
        go-version: '1.13.x' # The Go version to download (if necessary) and use.

    - run: go test ./...
    - run: go build -o bin/main cmd/main.go


    # Setup gcloud CLI
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '270.0.0'
        service_account_email: ${{ secrets.GKE_EMAIL }}
        service_account_key: ${{ secrets.GKE_KEY }}

    # Configure docker to use the gcloud command-line tool as a credential helper
    - name: GCloud Auth
      run: |
        # Set up docker to authenticate
        # via gcloud command-line tool.
        gcloud auth configure-docker

    # Build the Docker images
    - name: Build Core
      run: |
        docker build -t "$IMAGE_BASE"/go-gtfs-import:"$GITHUB_SHA" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" \
          -f Dockerfile .


    # Push the Docker images to Google Container Registry
    - name: Publish
      run: |
        docker tag "$IMAGE_BASE"/go-gtfs-import:"$GITHUB_SHA" "$IMAGE_BASE"/go-gtfs-import
        docker push "$IMAGE_BASE"/go-gtfs-import:"$GITHUB_SHA"
        docker push "$IMAGE_BASE"/go-gtfs-import
