name: Build and Deploy to GKE

on:
  push:
    branches:
    - master

env:
  GKE_PROJECT: ${{ secrets.GKE_PROJECT }}
  GKE_EMAIL: ${{ secrets.GKE_EMAIL }}
  GITHUB_SHA: ${{ github.sha }}
  GKE_ZONE: europe-west3-a
  GKE_CLUSTER: ab-cluster-1
  IMAGE_BASE: eu.gcr.io/${{ secrets.GKE_PROJECT }}/gtfs
  DOCKER_IMAGE: europe-west3-docker.pkg.dev/${{ secrets.GKE_PROJECT }}/gtfs/gtfs-import
  GO111MODULE: on
  CGO_ENABLED: 0

jobs:
  setup-build-publish-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - run: go test ./...
    - run: go build -o bin/main cmd/main.go


    # Build the Docker images
    - name: Build Core
      run: |
        docker build -t ${DOCKER_IMAGE}:${GITHUB_SHA} \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" \
          -f Dockerfile .

    - name: 'Authenticate with GKE'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GKE_KEY }}'

    - name: 'GCloud Authenticate Docker'
      run: gcloud auth configure-docker europe-west3-docker.pkg.dev
        
    # Push the Docker images to Google Container Registry
    - name: Publish
      run: |
        docker tag ${DOCKER_IMAGE}:"$GITHUB_SHA" ${DOCKER_IMAGE}
        docker push ${DOCKER_IMAGE}:"$GITHUB_SHA"
        docker push ${DOCKER_IMAGE}
